# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GalaxyModelOneD', [dirname(__file__)])
        except ImportError:
            import _GalaxyModelOneD
            return _GalaxyModelOneD
        if fp is not None:
            try:
                _mod = imp.load_module('_GalaxyModelOneD', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GalaxyModelOneD = swig_import_helper()
    del swig_import_helper
else:
    import _GalaxyModelOneD
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class GalaxyModelOneD(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GalaxyModelOneD, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GalaxyModelOneD, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _GalaxyModelOneD.new_GalaxyModelOneD(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _GalaxyModelOneD.delete_GalaxyModelOneD
    __del__ = lambda self: None

    def SetKnots(self, num):
        return _GalaxyModelOneD.GalaxyModelOneD_SetKnots(self, num)

    def LogLineOfSight(self, Smin):
        return _GalaxyModelOneD.GalaxyModelOneD_LogLineOfSight(self, Smin)

    def LinearLineOfSight(self):
        return _GalaxyModelOneD.GalaxyModelOneD_LinearLineOfSight(self)

    def SetExtinction(self, A, Z):
        return _GalaxyModelOneD.GalaxyModelOneD_SetExtinction(self, A, Z)

    def ExtinctionCoefficient(self, ak):
        return _GalaxyModelOneD.GalaxyModelOneD_ExtinctionCoefficient(self, ak)

    def CacheLimit(self, num):
        return _GalaxyModelOneD.GalaxyModelOneD_CacheLimit(self, num)

    def ModelLimits(self, amin, amax, hmin, hmax):
        return _GalaxyModelOneD.GalaxyModelOneD_ModelLimits(self, amin, amax, hmin, hmax)

    def MaximumDistance(self, rmax):
        return _GalaxyModelOneD.GalaxyModelOneD_MaximumDistance(self, rmax)

    def Initialize(self, *args):
        return _GalaxyModelOneD.GalaxyModelOneD_Initialize(self, *args)

    def ResetCache(self):
        return _GalaxyModelOneD.GalaxyModelOneD_ResetCache(self)

    def NormEval(self, x, y, d=None):
        return _GalaxyModelOneD.GalaxyModelOneD_NormEval(self, x, y, d)

    def NormEvalMeasure(self, x, y):
        return _GalaxyModelOneD.GalaxyModelOneD_NormEvalMeasure(self, x, y)

    def Evaluate(self, x, y, d=None):
        return _GalaxyModelOneD.GalaxyModelOneD_Evaluate(self, x, y, d)

    def ParameterLabels(self):
        return _GalaxyModelOneD.GalaxyModelOneD_ParameterLabels(self)
    __swig_setmethods__["LMAG"] = _GalaxyModelOneD.GalaxyModelOneD_LMAG_set
    __swig_getmethods__["LMAG"] = _GalaxyModelOneD.GalaxyModelOneD_LMAG_get
    if _newclass:
        LMAG = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_LMAG_get, _GalaxyModelOneD.GalaxyModelOneD_LMAG_set)
    __swig_setmethods__["HMAG"] = _GalaxyModelOneD.GalaxyModelOneD_HMAG_set
    __swig_getmethods__["HMAG"] = _GalaxyModelOneD.GalaxyModelOneD_HMAG_get
    if _newclass:
        HMAG = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_HMAG_get, _GalaxyModelOneD.GalaxyModelOneD_HMAG_set)
    __swig_setmethods__["A1"] = _GalaxyModelOneD.GalaxyModelOneD_A1_set
    __swig_getmethods__["A1"] = _GalaxyModelOneD.GalaxyModelOneD_A1_get
    if _newclass:
        A1 = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_A1_get, _GalaxyModelOneD.GalaxyModelOneD_A1_set)
    __swig_setmethods__["Z1"] = _GalaxyModelOneD.GalaxyModelOneD_Z1_set
    __swig_getmethods__["Z1"] = _GalaxyModelOneD.GalaxyModelOneD_Z1_get
    if _newclass:
        Z1 = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_Z1_get, _GalaxyModelOneD.GalaxyModelOneD_Z1_set)
    __swig_setmethods__["K0"] = _GalaxyModelOneD.GalaxyModelOneD_K0_set
    __swig_getmethods__["K0"] = _GalaxyModelOneD.GalaxyModelOneD_K0_get
    if _newclass:
        K0 = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_K0_get, _GalaxyModelOneD.GalaxyModelOneD_K0_set)
    __swig_setmethods__["SIGK"] = _GalaxyModelOneD.GalaxyModelOneD_SIGK_set
    __swig_getmethods__["SIGK"] = _GalaxyModelOneD.GalaxyModelOneD_SIGK_get
    if _newclass:
        SIGK = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_SIGK_get, _GalaxyModelOneD.GalaxyModelOneD_SIGK_set)
    __swig_setmethods__["NUM"] = _GalaxyModelOneD.GalaxyModelOneD_NUM_set
    __swig_getmethods__["NUM"] = _GalaxyModelOneD.GalaxyModelOneD_NUM_get
    if _newclass:
        NUM = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_NUM_get, _GalaxyModelOneD.GalaxyModelOneD_NUM_set)
    __swig_setmethods__["ALPHA"] = _GalaxyModelOneD.GalaxyModelOneD_ALPHA_set
    __swig_getmethods__["ALPHA"] = _GalaxyModelOneD.GalaxyModelOneD_ALPHA_get
    if _newclass:
        ALPHA = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_ALPHA_get, _GalaxyModelOneD.GalaxyModelOneD_ALPHA_set)
    __swig_setmethods__["BETA"] = _GalaxyModelOneD.GalaxyModelOneD_BETA_set
    __swig_getmethods__["BETA"] = _GalaxyModelOneD.GalaxyModelOneD_BETA_get
    if _newclass:
        BETA = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_BETA_get, _GalaxyModelOneD.GalaxyModelOneD_BETA_set)
    __swig_setmethods__["R0"] = _GalaxyModelOneD.GalaxyModelOneD_R0_set
    __swig_getmethods__["R0"] = _GalaxyModelOneD.GalaxyModelOneD_R0_get
    if _newclass:
        R0 = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_R0_get, _GalaxyModelOneD.GalaxyModelOneD_R0_set)
    __swig_setmethods__["RMAX"] = _GalaxyModelOneD.GalaxyModelOneD_RMAX_set
    __swig_getmethods__["RMAX"] = _GalaxyModelOneD.GalaxyModelOneD_RMAX_get
    if _newclass:
        RMAX = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_RMAX_get, _GalaxyModelOneD.GalaxyModelOneD_RMAX_set)
    __swig_setmethods__["AK"] = _GalaxyModelOneD.GalaxyModelOneD_AK_set
    __swig_getmethods__["AK"] = _GalaxyModelOneD.GalaxyModelOneD_AK_get
    if _newclass:
        AK = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_AK_get, _GalaxyModelOneD.GalaxyModelOneD_AK_set)
    __swig_setmethods__["AMIN"] = _GalaxyModelOneD.GalaxyModelOneD_AMIN_set
    __swig_getmethods__["AMIN"] = _GalaxyModelOneD.GalaxyModelOneD_AMIN_get
    if _newclass:
        AMIN = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_AMIN_get, _GalaxyModelOneD.GalaxyModelOneD_AMIN_set)
    __swig_setmethods__["AMAX"] = _GalaxyModelOneD.GalaxyModelOneD_AMAX_set
    __swig_getmethods__["AMAX"] = _GalaxyModelOneD.GalaxyModelOneD_AMAX_get
    if _newclass:
        AMAX = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_AMAX_get, _GalaxyModelOneD.GalaxyModelOneD_AMAX_set)
    __swig_setmethods__["HMIN"] = _GalaxyModelOneD.GalaxyModelOneD_HMIN_set
    __swig_getmethods__["HMIN"] = _GalaxyModelOneD.GalaxyModelOneD_HMIN_get
    if _newclass:
        HMIN = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_HMIN_get, _GalaxyModelOneD.GalaxyModelOneD_HMIN_set)
    __swig_setmethods__["HMAX"] = _GalaxyModelOneD.GalaxyModelOneD_HMAX_set
    __swig_getmethods__["HMAX"] = _GalaxyModelOneD.GalaxyModelOneD_HMAX_get
    if _newclass:
        HMAX = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_HMAX_get, _GalaxyModelOneD.GalaxyModelOneD_HMAX_set)
    __swig_setmethods__["logs"] = _GalaxyModelOneD.GalaxyModelOneD_logs_set
    __swig_getmethods__["logs"] = _GalaxyModelOneD.GalaxyModelOneD_logs_get
    if _newclass:
        logs = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_logs_get, _GalaxyModelOneD.GalaxyModelOneD_logs_set)
    __swig_setmethods__["smin"] = _GalaxyModelOneD.GalaxyModelOneD_smin_set
    __swig_getmethods__["smin"] = _GalaxyModelOneD.GalaxyModelOneD_smin_get
    if _newclass:
        smin = _swig_property(_GalaxyModelOneD.GalaxyModelOneD_smin_get, _GalaxyModelOneD.GalaxyModelOneD_smin_set)
GalaxyModelOneD_swigregister = _GalaxyModelOneD.GalaxyModelOneD_swigregister
GalaxyModelOneD_swigregister(GalaxyModelOneD)
cvar = _GalaxyModelOneD.cvar

# This file is compatible with both classic and new-style classes.


