# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GaussTestLikelihoodFunctionMulti', [dirname(__file__)])
        except ImportError:
            import _GaussTestLikelihoodFunctionMulti
            return _GaussTestLikelihoodFunctionMulti
        if fp is not None:
            try:
                _mod = imp.load_module('_GaussTestLikelihoodFunctionMulti', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GaussTestLikelihoodFunctionMulti = swig_import_helper()
    del swig_import_helper
else:
    import _GaussTestLikelihoodFunctionMulti
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class GaussTestLikelihoodFunctionMulti(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GaussTestLikelihoodFunctionMulti, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GaussTestLikelihoodFunctionMulti, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _GaussTestLikelihoodFunctionMulti.new_GaussTestLikelihoodFunctionMulti(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def SetLevels(self, n):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_SetLevels(self, n)

    def SetDim(self, n):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_SetDim(self, n)

    def PrintData(self):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_PrintData(self)

    def LikeProb(self, z, sd, norm, t, s, indx):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_LikeProb(self, z, sd, norm, t, s, indx)

    def CumuProb(self, z, sd, norm, t, s, indx, f):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_CumuProb(self, z, sd, norm, t, s, indx, f)

    def ParameterDescription(self, i):
        return _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_ParameterDescription(self, i)
    __swig_destroy__ = _GaussTestLikelihoodFunctionMulti.delete_GaussTestLikelihoodFunctionMulti
    __del__ = lambda self: None
GaussTestLikelihoodFunctionMulti_swigregister = _GaussTestLikelihoodFunctionMulti.GaussTestLikelihoodFunctionMulti_swigregister
GaussTestLikelihoodFunctionMulti_swigregister(GaussTestLikelihoodFunctionMulti)

# This file is compatible with both classic and new-style classes.


