# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_EnsembleStat', [dirname(__file__)])
        except ImportError:
            import _EnsembleStat
            return _EnsembleStat
        if fp is not None:
            try:
                _mod = imp.load_module('_EnsembleStat', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _EnsembleStat = swig_import_helper()
    del swig_import_helper
else:
    import _EnsembleStat
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Serializable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Serializable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Serializable, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _EnsembleStat.new_Serializable()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_Serializable
    __del__ = lambda self: None
Serializable_swigregister = _EnsembleStat.Serializable_swigregister
Serializable_swigregister(Serializable)

class Distribution(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Distribution, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Distribution, name)
    __repr__ = _swig_repr
    UniformAdd = _EnsembleStat.Distribution_UniformAdd
    UniformMult = _EnsembleStat.Distribution_UniformMult
    NormalAdd = _EnsembleStat.Distribution_NormalAdd
    NormalMult = _EnsembleStat.Distribution_NormalMult
    Undefined = _EnsembleStat.Distribution_Undefined

    def __init__(self):
        this = _EnsembleStat.new_Distribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_Distribution
    __del__ = lambda self: None

    def New(self):
        return _EnsembleStat.Distribution_New(self)

    def PDF(self, arg2):
        return _EnsembleStat.Distribution_PDF(self, arg2)

    def logPDF(self, arg2):
        return _EnsembleStat.Distribution_logPDF(self, arg2)

    def CDF(self, arg2):
        return _EnsembleStat.Distribution_CDF(self, arg2)

    def lower(self):
        return _EnsembleStat.Distribution_lower(self)

    def upper(self):
        return _EnsembleStat.Distribution_upper(self)

    def Mean(self):
        return _EnsembleStat.Distribution_Mean(self)

    def StdDev(self):
        return _EnsembleStat.Distribution_StdDev(self)

    def Moments(self, arg2):
        return _EnsembleStat.Distribution_Moments(self, arg2)

    def Sample(self):
        return _EnsembleStat.Distribution_Sample(self)

    def setWidth(self, x):
        return _EnsembleStat.Distribution_setWidth(self, x)

    def Type(self):
        return _EnsembleStat.Distribution_Type(self)

    def Dim(self):
        return _EnsembleStat.Distribution_Dim(self)
Distribution_swigregister = _EnsembleStat.Distribution_swigregister
Distribution_swigregister(Distribution)

class SampleDistribution(Distribution):
    __swig_setmethods__ = {}
    for _s in [Distribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SampleDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [Distribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SampleDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _EnsembleStat.delete_SampleDistribution
    __del__ = lambda self: None

    def CDF(self, arg2):
        return _EnsembleStat.SampleDistribution_CDF(self, arg2)

    def New(self):
        return _EnsembleStat.SampleDistribution_New(self)

    def AccumData(self, *args):
        return _EnsembleStat.SampleDistribution_AccumData(self, *args)

    def ComputeDistribution(self):
        return _EnsembleStat.SampleDistribution_ComputeDistribution(self)

    def numberData(self):
        return _EnsembleStat.SampleDistribution_numberData(self)

    def getValue(self, i):
        return _EnsembleStat.SampleDistribution_getValue(self, i)

    def getdim(self, i):
        return _EnsembleStat.SampleDistribution_getdim(self, i)

    def getRecordType(self):
        return _EnsembleStat.SampleDistribution_getRecordType(self)

    def getDataSetSize(self):
        return _EnsembleStat.SampleDistribution_getDataSetSize(self)
SampleDistribution_swigregister = _EnsembleStat.SampleDistribution_swigregister
SampleDistribution_swigregister(SampleDistribution)

class BinnedDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinnedDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BinnedDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _EnsembleStat.delete_BinnedDistribution
    __del__ = lambda self: None

    def New(self):
        return _EnsembleStat.BinnedDistribution_New(self)

    def getLow(self, i):
        return _EnsembleStat.BinnedDistribution_getLow(self, i)

    def getHigh(self, i):
        return _EnsembleStat.BinnedDistribution_getHigh(self, i)

    def CDF(self, arg2):
        return _EnsembleStat.BinnedDistribution_CDF(self, arg2)
BinnedDistribution_swigregister = _EnsembleStat.BinnedDistribution_swigregister
BinnedDistribution_swigregister(BinnedDistribution)

class PointDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PointDistribution, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _EnsembleStat.new_PointDistribution(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_PointDistribution
    __del__ = lambda self: None

    def New(self):
        return _EnsembleStat.PointDistribution_New(self)

    def getRecordType(self):
        return _EnsembleStat.PointDistribution_getRecordType(self)

    def AccumData(self, v, datapoint):
        return _EnsembleStat.PointDistribution_AccumData(self, v, datapoint)

    def getdim(self, i):
        return _EnsembleStat.PointDistribution_getdim(self, i)

    def numberData(self):
        return _EnsembleStat.PointDistribution_numberData(self)

    def getValue(self, i):
        return _EnsembleStat.PointDistribution_getValue(self, i)

    def Point(self):
        return _EnsembleStat.PointDistribution_Point(self)

    def CDF(self, v):
        return _EnsembleStat.PointDistribution_CDF(self, v)
PointDistribution_swigregister = _EnsembleStat.PointDistribution_swigregister
PointDistribution_swigregister(PointDistribution)

class NullDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, NullDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, NullDistribution, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _EnsembleStat.new_NullDistribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_NullDistribution
    __del__ = lambda self: None

    def New(self):
        return _EnsembleStat.NullDistribution_New(self)
NullDistribution_swigregister = _EnsembleStat.NullDistribution_swigregister
NullDistribution_swigregister(NullDistribution)

class StateData(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StateData, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StateData, name)
    __repr__ = _swig_repr
    __swig_setmethods__["prob"] = _EnsembleStat.StateData_prob_set
    __swig_getmethods__["prob"] = _EnsembleStat.StateData_prob_get
    if _newclass:
        prob = _swig_property(_EnsembleStat.StateData_prob_get, _EnsembleStat.StateData_prob_set)
    __swig_setmethods__["p"] = _EnsembleStat.StateData_p_set
    __swig_getmethods__["p"] = _EnsembleStat.StateData_p_get
    if _newclass:
        p = _swig_property(_EnsembleStat.StateData_p_get, _EnsembleStat.StateData_p_set)

    def __init__(self, *args):
        this = _EnsembleStat.new_StateData(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def Broadcast(self):
        return _EnsembleStat.StateData_Broadcast(self)
    __swig_destroy__ = _EnsembleStat.delete_StateData
    __del__ = lambda self: None
StateData_swigregister = _EnsembleStat.StateData_swigregister
StateData_swigregister(StateData)

class PairIndex(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PairIndex, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PairIndex, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _EnsembleStat.new_PairIndex()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_setmethods__["index"] = _EnsembleStat.PairIndex_index_set
    __swig_getmethods__["index"] = _EnsembleStat.PairIndex_index_get
    if _newclass:
        index = _swig_property(_EnsembleStat.PairIndex_index_get, _EnsembleStat.PairIndex_index_set)
    __swig_setmethods__["value"] = _EnsembleStat.PairIndex_value_set
    __swig_getmethods__["value"] = _EnsembleStat.PairIndex_value_get
    if _newclass:
        value = _swig_property(_EnsembleStat.PairIndex_value_get, _EnsembleStat.PairIndex_value_set)

    def __eq__(self, t):
        return _EnsembleStat.PairIndex___eq__(self, t)
    __swig_destroy__ = _EnsembleStat.delete_PairIndex
    __del__ = lambda self: None
PairIndex_swigregister = _EnsembleStat.PairIndex_swigregister
PairIndex_swigregister(PairIndex)

class StateCache(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, StateCache, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, StateCache, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _EnsembleStat.new_StateCache(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_StateCache
    __del__ = lambda self: None

    def Mean(self, m):
        return _EnsembleStat.StateCache_Mean(self, m)

    def Sample(self, m):
        return _EnsembleStat.StateCache_Sample(self, m)

    def logPDF(self, P):
        return _EnsembleStat.StateCache_logPDF(self, P)

    def size(self):
        return _EnsembleStat.StateCache_size(self)

    def stateSize(self):
        return _EnsembleStat.StateCache_stateSize(self)
StateCache_swigregister = _EnsembleStat.StateCache_swigregister
StateCache_swigregister(StateCache)

class Ensemble(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Ensemble, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Ensemble, name)
    __repr__ = _swig_repr
    __swig_setmethods__["verbose_debug"] = _EnsembleStat.Ensemble_verbose_debug_set
    __swig_getmethods__["verbose_debug"] = _EnsembleStat.Ensemble_verbose_debug_get
    if _newclass:
        verbose_debug = _swig_property(_EnsembleStat.Ensemble_verbose_debug_get, _EnsembleStat.Ensemble_verbose_debug_set)
    __swig_setmethods__["verbose_default"] = _EnsembleStat.Ensemble_verbose_default_set
    __swig_getmethods__["verbose_default"] = _EnsembleStat.Ensemble_verbose_default_get
    if _newclass:
        verbose_default = _swig_property(_EnsembleStat.Ensemble_verbose_default_get, _EnsembleStat.Ensemble_verbose_default_set)
    __swig_setmethods__["keep"] = _EnsembleStat.Ensemble_keep_set
    __swig_getmethods__["keep"] = _EnsembleStat.Ensemble_keep_get
    if _newclass:
        keep = _swig_property(_EnsembleStat.Ensemble_keep_get, _EnsembleStat.Ensemble_keep_set)
    __swig_setmethods__["minsub"] = _EnsembleStat.Ensemble_minsub_set
    __swig_getmethods__["minsub"] = _EnsembleStat.Ensemble_minsub_get
    if _newclass:
        minsub = _swig_property(_EnsembleStat.Ensemble_minsub_get, _EnsembleStat.Ensemble_minsub_set)
    __swig_setmethods__["thresh"] = _EnsembleStat.Ensemble_thresh_set
    __swig_getmethods__["thresh"] = _EnsembleStat.Ensemble_thresh_get
    if _newclass:
        thresh = _swig_property(_EnsembleStat.Ensemble_thresh_get, _EnsembleStat.Ensemble_thresh_set)
    __swig_setmethods__["continuous"] = _EnsembleStat.Ensemble_continuous_set
    __swig_getmethods__["continuous"] = _EnsembleStat.Ensemble_continuous_get
    if _newclass:
        continuous = _swig_property(_EnsembleStat.Ensemble_continuous_get, _EnsembleStat.Ensemble_continuous_set)
    __swig_setmethods__["key_pos"] = _EnsembleStat.Ensemble_key_pos_set
    __swig_getmethods__["key_pos"] = _EnsembleStat.Ensemble_key_pos_get
    if _newclass:
        key_pos = _swig_property(_EnsembleStat.Ensemble_key_pos_get, _EnsembleStat.Ensemble_key_pos_set)

    def __init__(self, *args):
        this = _EnsembleStat.new_Ensemble(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_Ensemble
    __del__ = lambda self: None

    def Reset(self, *args):
        return _EnsembleStat.Ensemble_Reset(self, *args)

    def setDimensions(self, si):
        return _EnsembleStat.Ensemble_setDimensions(self, si)

    def setContinuous(self):
        return _EnsembleStat.Ensemble_setContinuous(self)

    def setMaxRange(self):
        return _EnsembleStat.Ensemble_setMaxRange(self)

    def setNKeep(self, n):
        return _EnsembleStat.Ensemble_setNKeep(self, n)

    def Order(self, n):
        return _EnsembleStat.Ensemble_Order(self, n)

    def setVerboseOn(self):
        return _EnsembleStat.Ensemble_setVerboseOn(self)

    def setVerboseOff(self):
        return _EnsembleStat.Ensemble_setVerboseOff(self)

    def setVerboseDebugOn(self):
        return _EnsembleStat.Ensemble_setVerboseDebugOn(self)

    def setVerboseDebugOff(self):
        return _EnsembleStat.Ensemble_setVerboseDebugOff(self)

    def AccumData(self, *args):
        return _EnsembleStat.Ensemble_AccumData(self, *args)

    def AccumulateData(self, v, datapoint):
        return _EnsembleStat.Ensemble_AccumulateData(self, v, datapoint)

    def ComputeDistribution(self, *args):
        return _EnsembleStat.Ensemble_ComputeDistribution(self, *args)

    def stats(self, n, m, s):
        return _EnsembleStat.Ensemble_stats(self, n, m, s)

    def Nstates(self):
        return _EnsembleStat.Ensemble_Nstates(self)

    def Npopped(self):
        return _EnsembleStat.Ensemble_Npopped(self)

    def PDFSubspace(self, m):
        return _EnsembleStat.Ensemble_PDFSubspace(self, m)

    def getValidSubspaceMixtures(self):
        return _EnsembleStat.Ensemble_getValidSubspaceMixtures(self)

    def getStates(self):
        return _EnsembleStat.Ensemble_getStates(self)

    def getStateInfo(self):
        return _EnsembleStat.Ensemble_getStateInfo(self)

    def logPDF(self, p):
        return _EnsembleStat.Ensemble_logPDF(self, p)

    def logPDFMarginal(self, m, n, V):
        return _EnsembleStat.Ensemble_logPDFMarginal(self, m, n, V)

    def New(self):
        return _EnsembleStat.Ensemble_New(self)

    def StdDev(self, *args):
        return _EnsembleStat.Ensemble_StdDev(self, *args)

    def Mean(self, *args):
        return _EnsembleStat.Ensemble_Mean(self, *args)

    def Sample(self, *args):
        return _EnsembleStat.Ensemble_Sample(self, *args)

    def sampleSubspace(self):
        return _EnsembleStat.Ensemble_sampleSubspace(self)

    def Width(self, m):
        return _EnsembleStat.Ensemble_Width(self, m)

    def WidthVector(self, m):
        return _EnsembleStat.Ensemble_WidthVector(self, m)

    def printWidth(self, *args):
        return _EnsembleStat.Ensemble_printWidth(self, *args)

    def StdDevMarginal(self, m, n):
        return _EnsembleStat.Ensemble_StdDevMarginal(self, m, n)

    def MeanMarginal(self, m, n):
        return _EnsembleStat.Ensemble_MeanMarginal(self, m, n)

    def SampleMarginal(self, m, n):
        return _EnsembleStat.Ensemble_SampleMarginal(self, m, n)

    def WidthMarginal(self, m, n):
        return _EnsembleStat.Ensemble_WidthMarginal(self, m, n)

    def PrintDiag(self, *args):
        return _EnsembleStat.Ensemble_PrintDiag(self, *args)

    def Exists(self, m):
        return _EnsembleStat.Ensemble_Exists(self, m)

    def Broadcast(self):
        return _EnsembleStat.Ensemble_Broadcast(self)

    def enableDump(self):
        return _EnsembleStat.Ensemble_enableDump(self)

    def disableDump(self):
        return _EnsembleStat.Ensemble_disableDump(self)

    def binaryDump(self):
        return _EnsembleStat.Ensemble_binaryDump(self)

    def asciiDump(self):
        return _EnsembleStat.Ensemble_asciiDump(self)

    def statesToFile(self, filename, binary):
        return _EnsembleStat.Ensemble_statesToFile(self, filename, binary)

    def dumpStates(self, *args):
        return _EnsembleStat.Ensemble_dumpStates(self, *args)

    def PrintDensity(self, *args):
        return _EnsembleStat.Ensemble_PrintDensity(self, *args)

    def getMaxLikeState(self):
        return _EnsembleStat.Ensemble_getMaxLikeState(self)

    def getMaxProbState(self):
        return _EnsembleStat.Ensemble_getMaxProbState(self)
Ensemble_swigregister = _EnsembleStat.Ensemble_swigregister
Ensemble_swigregister(Ensemble)
cvar = _EnsembleStat.cvar

class EnsembleStat(Ensemble):
    __swig_setmethods__ = {}
    for _s in [Ensemble]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, EnsembleStat, name, value)
    __swig_getmethods__ = {}
    for _s in [Ensemble]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, EnsembleStat, name)
    __repr__ = _swig_repr
    __swig_setmethods__["minsub"] = _EnsembleStat.EnsembleStat_minsub_set
    __swig_getmethods__["minsub"] = _EnsembleStat.EnsembleStat_minsub_get
    if _newclass:
        minsub = _swig_property(_EnsembleStat.EnsembleStat_minsub_get, _EnsembleStat.EnsembleStat_minsub_set)

    def __init__(self, *args):
        this = _EnsembleStat.new_EnsembleStat(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _EnsembleStat.delete_EnsembleStat
    __del__ = lambda self: None

    def Reset(self, *args):
        return _EnsembleStat.EnsembleStat_Reset(self, *args)

    def setDimensions(self, si):
        return _EnsembleStat.EnsembleStat_setDimensions(self, si)
    __swig_setmethods__["covar"] = _EnsembleStat.EnsembleStat_covar_set
    __swig_getmethods__["covar"] = _EnsembleStat.EnsembleStat_covar_get
    if _newclass:
        covar = _swig_property(_EnsembleStat.EnsembleStat_covar_get, _EnsembleStat.EnsembleStat_covar_set)
    __swig_setmethods__["covarM"] = _EnsembleStat.EnsembleStat_covarM_set
    __swig_getmethods__["covarM"] = _EnsembleStat.EnsembleStat_covarM_get
    if _newclass:
        covarM = _swig_property(_EnsembleStat.EnsembleStat_covarM_get, _EnsembleStat.EnsembleStat_covarM_set)
    __swig_setmethods__["Teigen"] = _EnsembleStat.EnsembleStat_Teigen_set
    __swig_getmethods__["Teigen"] = _EnsembleStat.EnsembleStat_Teigen_get
    if _newclass:
        Teigen = _swig_property(_EnsembleStat.EnsembleStat_Teigen_get, _EnsembleStat.EnsembleStat_Teigen_set)
    __swig_setmethods__["TeigeM"] = _EnsembleStat.EnsembleStat_TeigeM_set
    __swig_getmethods__["TeigeM"] = _EnsembleStat.EnsembleStat_TeigeM_get
    if _newclass:
        TeigeM = _swig_property(_EnsembleStat.EnsembleStat_TeigeM_get, _EnsembleStat.EnsembleStat_TeigeM_set)
    __swig_setmethods__["eigen"] = _EnsembleStat.EnsembleStat_eigen_set
    __swig_getmethods__["eigen"] = _EnsembleStat.EnsembleStat_eigen_get
    if _newclass:
        eigen = _swig_property(_EnsembleStat.EnsembleStat_eigen_get, _EnsembleStat.EnsembleStat_eigen_set)
    __swig_setmethods__["eigenM"] = _EnsembleStat.EnsembleStat_eigenM_set
    __swig_getmethods__["eigenM"] = _EnsembleStat.EnsembleStat_eigenM_get
    if _newclass:
        eigenM = _swig_property(_EnsembleStat.EnsembleStat_eigenM_get, _EnsembleStat.EnsembleStat_eigenM_set)
    __swig_setmethods__["mean"] = _EnsembleStat.EnsembleStat_mean_set
    __swig_getmethods__["mean"] = _EnsembleStat.EnsembleStat_mean_get
    if _newclass:
        mean = _swig_property(_EnsembleStat.EnsembleStat_mean_get, _EnsembleStat.EnsembleStat_mean_set)
    __swig_setmethods__["meanM"] = _EnsembleStat.EnsembleStat_meanM_set
    __swig_getmethods__["meanM"] = _EnsembleStat.EnsembleStat_meanM_get
    if _newclass:
        meanM = _swig_property(_EnsembleStat.EnsembleStat_meanM_get, _EnsembleStat.EnsembleStat_meanM_set)
    __swig_setmethods__["evals"] = _EnsembleStat.EnsembleStat_evals_set
    __swig_getmethods__["evals"] = _EnsembleStat.EnsembleStat_evals_get
    if _newclass:
        evals = _swig_property(_EnsembleStat.EnsembleStat_evals_get, _EnsembleStat.EnsembleStat_evals_set)
    __swig_setmethods__["evalsM"] = _EnsembleStat.EnsembleStat_evalsM_set
    __swig_getmethods__["evalsM"] = _EnsembleStat.EnsembleStat_evalsM_get
    if _newclass:
        evalsM = _swig_property(_EnsembleStat.EnsembleStat_evalsM_get, _EnsembleStat.EnsembleStat_evalsM_set)

    def ComputeDistribution(self, *args):
        return _EnsembleStat.EnsembleStat_ComputeDistribution(self, *args)

    def ComputeDistributionMarginal(self, out):
        return _EnsembleStat.EnsembleStat_ComputeDistributionMarginal(self, out)

    def trim_location(self, m):
        return _EnsembleStat.EnsembleStat_trim_location(self, m)

    def trim_location_marginal(self, m, n):
        return _EnsembleStat.EnsembleStat_trim_location_marginal(self, m, n)

    def New(self):
        return _EnsembleStat.EnsembleStat_New(self)

    def logPDF(self, arg2):
        return _EnsembleStat.EnsembleStat_logPDF(self, arg2)

    def logPDFMarginal(self, m, n, V):
        return _EnsembleStat.EnsembleStat_logPDFMarginal(self, m, n, V)

    def PDF(self, *args):
        return _EnsembleStat.EnsembleStat_PDF(self, *args)

    def lower(self):
        return _EnsembleStat.EnsembleStat_lower(self)

    def upper(self):
        return _EnsembleStat.EnsembleStat_upper(self)

    def Mean(self, m):
        return _EnsembleStat.EnsembleStat_Mean(self, m)

    def StdDev(self, m):
        return _EnsembleStat.EnsembleStat_StdDev(self, m)

    def Moments(self, m, k):
        return _EnsembleStat.EnsembleStat_Moments(self, m, k)

    def Sample(self, m):
        return _EnsembleStat.EnsembleStat_Sample(self, m)

    def SampleOne(self, m, j):
        return _EnsembleStat.EnsembleStat_SampleOne(self, m, j)

    def StdDevMarginal(self, m, n):
        return _EnsembleStat.EnsembleStat_StdDevMarginal(self, m, n)

    def MeanMarginal(self, m, n):
        return _EnsembleStat.EnsembleStat_MeanMarginal(self, m, n)

    def SampleMarginal(self, m, n):
        return _EnsembleStat.EnsembleStat_SampleMarginal(self, m, n)

    def WidthMarginal(self, m, n):
        return _EnsembleStat.EnsembleStat_WidthMarginal(self, m, n)

    def PrintDiag(self, *args):
        return _EnsembleStat.EnsembleStat_PrintDiag(self, *args)

    def PrintDensity(self, dim1, dim2, num1, num2, file):
        return _EnsembleStat.EnsembleStat_PrintDensity(self, dim1, dim2, num1, num2, file)
EnsembleStat_swigregister = _EnsembleStat.EnsembleStat_swigregister
EnsembleStat_swigregister(EnsembleStat)

# This file is compatible with both classic and new-style classes.


