# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_FunnelTest', [dirname(__file__)])
        except ImportError:
            import _FunnelTest
            return _FunnelTest
        if fp is not None:
            try:
                _mod = imp.load_module('_FunnelTest', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _FunnelTest = swig_import_helper()
    del swig_import_helper
else:
    import _FunnelTest
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Serializable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Serializable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Serializable, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _FunnelTest.new_Serializable()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _FunnelTest.delete_Serializable
    __del__ = lambda self: None
Serializable_swigregister = _FunnelTest.Serializable_swigregister
Serializable_swigregister(Serializable)

class Funct1d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Funct1d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Funct1d, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def G(self, arg2):
        return _FunnelTest.Funct1d_G(self, arg2)
    __swig_destroy__ = _FunnelTest.delete_Funct1d
    __del__ = lambda self: None
Funct1d_swigregister = _FunnelTest.Funct1d_swigregister
Funct1d_swigregister(Funct1d)

class LikelihoodFunction(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, LikelihoodFunction, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, LikelihoodFunction, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["threshval"] = _FunnelTest.LikelihoodFunction_threshval_set
    __swig_getmethods__["threshval"] = _FunnelTest.LikelihoodFunction_threshval_get
    if _newclass:
        threshval = _swig_property(_FunnelTest.LikelihoodFunction_threshval_get, _FunnelTest.LikelihoodFunction_threshval_set)

    def CumuProb(self, z, sd, norm, t, s, indx, f):
        return _FunnelTest.LikelihoodFunction_CumuProb(self, z, sd, norm, t, s, indx, f)

    def LikeProb(self, *args):
        return _FunnelTest.LikelihoodFunction_LikeProb(self, *args)

    def ParameterDescription(self, i):
        return _FunnelTest.LikelihoodFunction_ParameterDescription(self, i)
    __swig_destroy__ = _FunnelTest.delete_LikelihoodFunction
    __del__ = lambda self: None
LikelihoodFunction_swigregister = _FunnelTest.LikelihoodFunction_swigregister
LikelihoodFunction_swigregister(LikelihoodFunction)
cvar = _FunnelTest.cvar

class FunnelTest(LikelihoodFunction):
    __swig_setmethods__ = {}
    for _s in [LikelihoodFunction]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, FunnelTest, name, value)
    __swig_getmethods__ = {}
    for _s in [LikelihoodFunction]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, FunnelTest, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _FunnelTest.new_FunnelTest(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _FunnelTest.delete_FunnelTest
    __del__ = lambda self: None

    def LikeProb(self, z, sd, norm, t, s, indx):
        return _FunnelTest.FunnelTest_LikeProb(self, z, sd, norm, t, s, indx)

    def CumuProb(self, z, sd, norm, t, s, indx, f):
        return _FunnelTest.FunnelTest_CumuProb(self, z, sd, norm, t, s, indx, f)

    def ParameterDescription(self, i):
        return _FunnelTest.FunnelTest_ParameterDescription(self, i)
FunnelTest_swigregister = _FunnelTest.FunnelTest_swigregister
FunnelTest_swigregister(FunnelTest)

# This file is compatible with both classic and new-style classes.


