# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_InitialMixturePrior', [dirname(__file__)])
        except ImportError:
            import _InitialMixturePrior
            return _InitialMixturePrior
        if fp is not None:
            try:
                _mod = imp.load_module('_InitialMixturePrior', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _InitialMixturePrior = swig_import_helper()
    del swig_import_helper
else:
    import _InitialMixturePrior
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Serializable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Serializable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Serializable, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _InitialMixturePrior.new_Serializable()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _InitialMixturePrior.delete_Serializable
    __del__ = lambda self: None
Serializable_swigregister = _InitialMixturePrior.Serializable_swigregister
Serializable_swigregister(Serializable)

class Distribution(Serializable):
    __swig_setmethods__ = {}
    for _s in [Serializable]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Distribution, name, value)
    __swig_getmethods__ = {}
    for _s in [Serializable]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Distribution, name)
    __repr__ = _swig_repr
    UniformAdd = _InitialMixturePrior.Distribution_UniformAdd
    UniformMult = _InitialMixturePrior.Distribution_UniformMult
    NormalAdd = _InitialMixturePrior.Distribution_NormalAdd
    NormalMult = _InitialMixturePrior.Distribution_NormalMult
    Undefined = _InitialMixturePrior.Distribution_Undefined

    def __init__(self):
        this = _InitialMixturePrior.new_Distribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _InitialMixturePrior.delete_Distribution
    __del__ = lambda self: None

    def New(self):
        return _InitialMixturePrior.Distribution_New(self)

    def PDF(self, arg2):
        return _InitialMixturePrior.Distribution_PDF(self, arg2)

    def logPDF(self, arg2):
        return _InitialMixturePrior.Distribution_logPDF(self, arg2)

    def CDF(self, arg2):
        return _InitialMixturePrior.Distribution_CDF(self, arg2)

    def lower(self):
        return _InitialMixturePrior.Distribution_lower(self)

    def upper(self):
        return _InitialMixturePrior.Distribution_upper(self)

    def Mean(self):
        return _InitialMixturePrior.Distribution_Mean(self)

    def StdDev(self):
        return _InitialMixturePrior.Distribution_StdDev(self)

    def Moments(self, arg2):
        return _InitialMixturePrior.Distribution_Moments(self, arg2)

    def Sample(self):
        return _InitialMixturePrior.Distribution_Sample(self)

    def setWidth(self, x):
        return _InitialMixturePrior.Distribution_setWidth(self, x)

    def Type(self):
        return _InitialMixturePrior.Distribution_Type(self)

    def Dim(self):
        return _InitialMixturePrior.Distribution_Dim(self)
Distribution_swigregister = _InitialMixturePrior.Distribution_swigregister
Distribution_swigregister(Distribution)

class SampleDistribution(Distribution):
    __swig_setmethods__ = {}
    for _s in [Distribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SampleDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [Distribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SampleDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _InitialMixturePrior.delete_SampleDistribution
    __del__ = lambda self: None

    def CDF(self, arg2):
        return _InitialMixturePrior.SampleDistribution_CDF(self, arg2)

    def New(self):
        return _InitialMixturePrior.SampleDistribution_New(self)

    def AccumData(self, *args):
        return _InitialMixturePrior.SampleDistribution_AccumData(self, *args)

    def ComputeDistribution(self):
        return _InitialMixturePrior.SampleDistribution_ComputeDistribution(self)

    def numberData(self):
        return _InitialMixturePrior.SampleDistribution_numberData(self)

    def getValue(self, i):
        return _InitialMixturePrior.SampleDistribution_getValue(self, i)

    def getdim(self, i):
        return _InitialMixturePrior.SampleDistribution_getdim(self, i)

    def getRecordType(self):
        return _InitialMixturePrior.SampleDistribution_getRecordType(self)

    def getDataSetSize(self):
        return _InitialMixturePrior.SampleDistribution_getDataSetSize(self)
SampleDistribution_swigregister = _InitialMixturePrior.SampleDistribution_swigregister
SampleDistribution_swigregister(SampleDistribution)

class BinnedDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinnedDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BinnedDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _InitialMixturePrior.delete_BinnedDistribution
    __del__ = lambda self: None

    def New(self):
        return _InitialMixturePrior.BinnedDistribution_New(self)

    def getLow(self, i):
        return _InitialMixturePrior.BinnedDistribution_getLow(self, i)

    def getHigh(self, i):
        return _InitialMixturePrior.BinnedDistribution_getHigh(self, i)

    def CDF(self, arg2):
        return _InitialMixturePrior.BinnedDistribution_CDF(self, arg2)
BinnedDistribution_swigregister = _InitialMixturePrior.BinnedDistribution_swigregister
BinnedDistribution_swigregister(BinnedDistribution)

class PointDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PointDistribution, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _InitialMixturePrior.new_PointDistribution(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _InitialMixturePrior.delete_PointDistribution
    __del__ = lambda self: None

    def New(self):
        return _InitialMixturePrior.PointDistribution_New(self)

    def getRecordType(self):
        return _InitialMixturePrior.PointDistribution_getRecordType(self)

    def AccumData(self, v, datapoint):
        return _InitialMixturePrior.PointDistribution_AccumData(self, v, datapoint)

    def getdim(self, i):
        return _InitialMixturePrior.PointDistribution_getdim(self, i)

    def numberData(self):
        return _InitialMixturePrior.PointDistribution_numberData(self)

    def getValue(self, i):
        return _InitialMixturePrior.PointDistribution_getValue(self, i)

    def Point(self):
        return _InitialMixturePrior.PointDistribution_Point(self)

    def CDF(self, v):
        return _InitialMixturePrior.PointDistribution_CDF(self, v)
PointDistribution_swigregister = _InitialMixturePrior.PointDistribution_swigregister
PointDistribution_swigregister(PointDistribution)

class NullDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, NullDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, NullDistribution, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _InitialMixturePrior.new_NullDistribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _InitialMixturePrior.delete_NullDistribution
    __del__ = lambda self: None

    def New(self):
        return _InitialMixturePrior.NullDistribution_New(self)
NullDistribution_swigregister = _InitialMixturePrior.NullDistribution_swigregister
NullDistribution_swigregister(NullDistribution)

class Prior(Distribution):
    __swig_setmethods__ = {}
    for _s in [Distribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Prior, name, value)
    __swig_getmethods__ = {}
    for _s in [Distribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Prior, name)
    __repr__ = _swig_repr
    __swig_setmethods__["width_factor"] = _InitialMixturePrior.Prior_width_factor_set
    __swig_getmethods__["width_factor"] = _InitialMixturePrior.Prior_width_factor_get
    if _newclass:
        width_factor = _swig_property(_InitialMixturePrior.Prior_width_factor_get, _InitialMixturePrior.Prior_width_factor_set)
    __swig_setmethods__["max_iter"] = _InitialMixturePrior.Prior_max_iter_set
    __swig_getmethods__["max_iter"] = _InitialMixturePrior.Prior_max_iter_get
    if _newclass:
        max_iter = _swig_property(_InitialMixturePrior.Prior_max_iter_get, _InitialMixturePrior.Prior_max_iter_set)

    def __init__(self, *args):
        this = _InitialMixturePrior.new_Prior(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _InitialMixturePrior.delete_Prior
    __del__ = lambda self: None

    def InitialStates(self, e):
        return _InitialMixturePrior.Prior_InitialStates(self, e)

    def SI(self):
        return _InitialMixturePrior.Prior_SI(self)

    def Dim(self):
        return _InitialMixturePrior.Prior_Dim(self)

    def New(self):
        return _InitialMixturePrior.Prior_New(self)

    def PDF(self, arg2):
        return _InitialMixturePrior.Prior_PDF(self, arg2)

    def logPDF(self, arg2):
        return _InitialMixturePrior.Prior_logPDF(self, arg2)

    def lower(self):
        return _InitialMixturePrior.Prior_lower(self)

    def upper(self):
        return _InitialMixturePrior.Prior_upper(self)

    def Mean(self):
        return _InitialMixturePrior.Prior_Mean(self)

    def StdDev(self):
        return _InitialMixturePrior.Prior_StdDev(self)

    def Moments(self, arg2):
        return _InitialMixturePrior.Prior_Moments(self, arg2)

    def Sample(self, *args):
        return _InitialMixturePrior.Prior_Sample(self, *args)

    def SamplePrior(self, arg2):
        return _InitialMixturePrior.Prior_SamplePrior(self, arg2)

    def SampleProposal(self, ch, width):
        return _InitialMixturePrior.Prior_SampleProposal(self, ch, width)

    def EnforceBounds(self, ch):
        return _InitialMixturePrior.Prior_EnforceBounds(self, ch)

    def EnforceBoundsState(self, s):
        return _InitialMixturePrior.Prior_EnforceBoundsState(self, s)
Prior_swigregister = _InitialMixturePrior.Prior_swigregister
Prior_swigregister(Prior)
cvar = _InitialMixturePrior.cvar

class MixturePrior(Prior):
    __swig_setmethods__ = {}
    for _s in [Prior]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MixturePrior, name, value)
    __swig_getmethods__ = {}
    for _s in [Prior]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MixturePrior, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["ITMAX"] = _InitialMixturePrior.MixturePrior_ITMAX_set
    __swig_getmethods__["ITMAX"] = _InitialMixturePrior.MixturePrior_ITMAX_get
    if _newclass:
        ITMAX = _swig_property(_InitialMixturePrior.MixturePrior_ITMAX_get, _InitialMixturePrior.MixturePrior_ITMAX_set)
    __swig_setmethods__["min_prob"] = _InitialMixturePrior.MixturePrior_min_prob_set
    __swig_getmethods__["min_prob"] = _InitialMixturePrior.MixturePrior_min_prob_get
    if _newclass:
        min_prob = _swig_property(_InitialMixturePrior.MixturePrior_min_prob_get, _InitialMixturePrior.MixturePrior_min_prob_set)
    __swig_destroy__ = _InitialMixturePrior.delete_MixturePrior
    __del__ = lambda self: None

    def setMaxIter(self, i):
        return _InitialMixturePrior.MixturePrior_setMaxIter(self, i)

    def New(self):
        return _InitialMixturePrior.MixturePrior_New(self)

    def PDF(self, arg2):
        return _InitialMixturePrior.MixturePrior_PDF(self, arg2)

    def logPDF(self, arg2):
        return _InitialMixturePrior.MixturePrior_logPDF(self, arg2)

    def logPDFMarginal(self, M, n, V):
        return _InitialMixturePrior.MixturePrior_logPDFMarginal(self, M, n, V)

    def lower(self):
        return _InitialMixturePrior.MixturePrior_lower(self)

    def upper(self):
        return _InitialMixturePrior.MixturePrior_upper(self)

    def SampleM(self):
        return _InitialMixturePrior.MixturePrior_SampleM(self)

    def Sample(self, *args):
        return _InitialMixturePrior.MixturePrior_Sample(self, *args)

    def SamplePrior(self, *args):
        return _InitialMixturePrior.MixturePrior_SamplePrior(self, *args)

    def SampleProposal(self, ch, width):
        return _InitialMixturePrior.MixturePrior_SampleProposal(self, ch, width)

    def BirthWeight(self, M):
        return _InitialMixturePrior.MixturePrior_BirthWeight(self, M)

    def BirthWeightPDF(self, M, p):
        return _InitialMixturePrior.MixturePrior_BirthWeightPDF(self, M, p)

    def Exists(self, m):
        return _InitialMixturePrior.MixturePrior_Exists(self, m)
MixturePrior_swigregister = _InitialMixturePrior.MixturePrior_swigregister
MixturePrior_swigregister(MixturePrior)

class InitialMixturePrior(MixturePrior):
    __swig_setmethods__ = {}
    for _s in [MixturePrior]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, InitialMixturePrior, name, value)
    __swig_getmethods__ = {}
    for _s in [MixturePrior]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, InitialMixturePrior, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _InitialMixturePrior.new_InitialMixturePrior(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def New(self):
        return _InitialMixturePrior.InitialMixturePrior_New(self)

    def PDF(self, arg2):
        return _InitialMixturePrior.InitialMixturePrior_PDF(self, arg2)

    def logPDF(self, arg2):
        return _InitialMixturePrior.InitialMixturePrior_logPDF(self, arg2)

    def logPDFMarginal(self, M, n, V):
        return _InitialMixturePrior.InitialMixturePrior_logPDFMarginal(self, M, n, V)

    def lower(self):
        return _InitialMixturePrior.InitialMixturePrior_lower(self)

    def upper(self):
        return _InitialMixturePrior.InitialMixturePrior_upper(self)

    def Mean(self, m):
        return _InitialMixturePrior.InitialMixturePrior_Mean(self, m)

    def StdDev(self, m):
        return _InitialMixturePrior.InitialMixturePrior_StdDev(self, m)

    def Moments(self, m, n):
        return _InitialMixturePrior.InitialMixturePrior_Moments(self, m, n)

    def Sample(self, m):
        return _InitialMixturePrior.InitialMixturePrior_Sample(self, m)

    def SamplePrior(self, *args):
        return _InitialMixturePrior.InitialMixturePrior_SamplePrior(self, *args)
    __swig_destroy__ = _InitialMixturePrior.delete_InitialMixturePrior
    __del__ = lambda self: None
InitialMixturePrior_swigregister = _InitialMixturePrior.InitialMixturePrior_swigregister
InitialMixturePrior_swigregister(InitialMixturePrior)

# This file is compatible with both classic and new-style classes.


