# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_SplatModel1d')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_SplatModel1d')
    _SplatModel1d = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SplatModel1d', [dirname(__file__)])
        except ImportError:
            import _SplatModel1d
            return _SplatModel1d
        if fp is not None:
            try:
                _mod = imp.load_module('_SplatModel1d', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SplatModel1d = swig_import_helper()
    del swig_import_helper
else:
    import _SplatModel1d
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SplatModel1d(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SplatModel1d, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SplatModel1d, name)
    __repr__ = _swig_repr
    __swig_setmethods__["SIGX"] = _SplatModel1d.SplatModel1d_SIGX_set
    __swig_getmethods__["SIGX"] = _SplatModel1d.SplatModel1d_SIGX_get
    if _newclass:
        SIGX = _swig_property(_SplatModel1d.SplatModel1d_SIGX_get, _SplatModel1d.SplatModel1d_SIGX_set)
    __swig_setmethods__["VALUE"] = _SplatModel1d.SplatModel1d_VALUE_set
    __swig_getmethods__["VALUE"] = _SplatModel1d.SplatModel1d_VALUE_get
    if _newclass:
        VALUE = _swig_property(_SplatModel1d.SplatModel1d_VALUE_get, _SplatModel1d.SplatModel1d_VALUE_set)

    def __init__(self, ndim, mdim):
        this = _SplatModel1d.new_SplatModel1d(ndim, mdim)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def setSIG(self, sigx):
        return _SplatModel1d.SplatModel1d_setSIG(self, sigx)

    def Initialize(self, *args):
        return _SplatModel1d.SplatModel1d_Initialize(self, *args)

    def NormEval(self, *args):
        return _SplatModel1d.SplatModel1d_NormEval(self, *args)

    def EvaluateBinned(self, x, y, d):
        return _SplatModel1d.SplatModel1d_EvaluateBinned(self, x, y, d)

    def EvaluatePoint(self, x, y, d):
        return _SplatModel1d.SplatModel1d_EvaluatePoint(self, x, y, d)

    def ParameterLabels(self):
        return _SplatModel1d.SplatModel1d_ParameterLabels(self)
    __swig_destroy__ = _SplatModel1d.delete_SplatModel1d
    __del__ = lambda self: None
SplatModel1d_swigregister = _SplatModel1d.SplatModel1d_swigregister
SplatModel1d_swigregister(SplatModel1d)
cvar = _SplatModel1d.cvar

class Model(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Model, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Model, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_setmethods__["quadtree"] = _SplatModel1d.Model_quadtree_set
    __swig_getmethods__["quadtree"] = _SplatModel1d.Model_quadtree_get
    if _newclass:
        quadtree = _swig_property(_SplatModel1d.Model_quadtree_get, _SplatModel1d.Model_quadtree_set)
    __swig_setmethods__["maxlevels"] = _SplatModel1d.Model_maxlevels_set
    __swig_getmethods__["maxlevels"] = _SplatModel1d.Model_maxlevels_get
    if _newclass:
        maxlevels = _swig_property(_SplatModel1d.Model_maxlevels_get, _SplatModel1d.Model_maxlevels_set)
    __swig_setmethods__["qeps"] = _SplatModel1d.Model_qeps_set
    __swig_getmethods__["qeps"] = _SplatModel1d.Model_qeps_get
    if _newclass:
        qeps = _swig_property(_SplatModel1d.Model_qeps_get, _SplatModel1d.Model_qeps_set)
    __swig_setmethods__["dX0"] = _SplatModel1d.Model_dX0_set
    __swig_getmethods__["dX0"] = _SplatModel1d.Model_dX0_get
    if _newclass:
        dX0 = _swig_property(_SplatModel1d.Model_dX0_get, _SplatModel1d.Model_dX0_set)
    __swig_setmethods__["dY0"] = _SplatModel1d.Model_dY0_set
    __swig_getmethods__["dY0"] = _SplatModel1d.Model_dY0_get
    if _newclass:
        dY0 = _swig_property(_SplatModel1d.Model_dY0_get, _SplatModel1d.Model_dY0_set)
    __swig_setmethods__["dX1"] = _SplatModel1d.Model_dX1_set
    __swig_getmethods__["dX1"] = _SplatModel1d.Model_dX1_get
    if _newclass:
        dX1 = _swig_property(_SplatModel1d.Model_dX1_get, _SplatModel1d.Model_dX1_set)
    __swig_setmethods__["dY1"] = _SplatModel1d.Model_dY1_set
    __swig_getmethods__["dY1"] = _SplatModel1d.Model_dY1_get
    if _newclass:
        dY1 = _swig_property(_SplatModel1d.Model_dY1_get, _SplatModel1d.Model_dY1_set)
    __swig_setmethods__["numX"] = _SplatModel1d.Model_numX_set
    __swig_getmethods__["numX"] = _SplatModel1d.Model_numX_get
    if _newclass:
        numX = _swig_property(_SplatModel1d.Model_numX_get, _SplatModel1d.Model_numX_set)
    __swig_setmethods__["numY"] = _SplatModel1d.Model_numY_set
    __swig_getmethods__["numY"] = _SplatModel1d.Model_numY_get
    if _newclass:
        numY = _swig_property(_SplatModel1d.Model_numY_get, _SplatModel1d.Model_numY_set)
    __swig_destroy__ = _SplatModel1d.delete_Model
    __del__ = lambda self: None

    def getParameterType(self):
        return _SplatModel1d.Model_getParameterType(self)

    def setNormKnots(self, nx, ny):
        return _SplatModel1d.Model_setNormKnots(self, nx, ny)

    def setQuadTreeParams(self, dx0, dy0, dx1, dy1, eps, mlev):
        return _SplatModel1d.Model_setQuadTreeParams(self, dx0, dy0, dx1, dy1, eps, mlev)

    def Initialize(self, arg2):
        return _SplatModel1d.Model_Initialize(self, arg2)

    def ResetCache(self):
        return _SplatModel1d.Model_ResetCache(self)

    def NormEval(self, *args):
        return _SplatModel1d.Model_NormEval(self, *args)

    def NormEvalMeasure(self, X, Y):
        return _SplatModel1d.Model_NormEvalMeasure(self, X, Y)

    def Evaluate(self, x, y, d):
        return _SplatModel1d.Model_Evaluate(self, x, y, d)

    def EvaluateBinned(self, x, y, d):
        return _SplatModel1d.Model_EvaluateBinned(self, x, y, d)

    def EvaluatePoint(self, x, y, d):
        return _SplatModel1d.Model_EvaluatePoint(self, x, y, d)

    def ParameterLabels(self):
        return _SplatModel1d.Model_ParameterLabels(self)

    def ExtendedLabels(self):
        return _SplatModel1d.Model_ExtendedLabels(self)
    binned = _SplatModel1d.Model_binned
    point = _SplatModel1d.Model_point
Model_swigregister = _SplatModel1d.Model_swigregister
Model_swigregister(Model)

class Serializable(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Serializable, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Serializable, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _SplatModel1d.new_Serializable()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _SplatModel1d.delete_Serializable
    __del__ = lambda self: None
Serializable_swigregister = _SplatModel1d.Serializable_swigregister
Serializable_swigregister(Serializable)

# This file is compatible with both classic and new-style classes.


