# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_SymTab')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_SymTab')
    _SymTab = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SymTab', [dirname(__file__)])
        except ImportError:
            import _SymTab
            return _SymTab
        if fp is not None:
            try:
                _mod = imp.load_module('_SymTab', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _SymTab = swig_import_helper()
    del swig_import_helper
else:
    import _SymTab
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SymTab(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SymTab, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SymTab, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _SymTab.new_SymTab()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def add_symbol(self, symbol, data):
        return _SymTab.SymTab_add_symbol(self, symbol, data)

    def get_symbol_value(self, symbol):
        return _SymTab.SymTab_get_symbol_value(self, symbol)

    def get_symbol_value_copy(self, symbol, data):
        return _SymTab.SymTab_get_symbol_value_copy(self, symbol, data)

    def print_value(self, outputstream, symbol):
        return _SymTab.SymTab_print_value(self, outputstream, symbol)

    def print_all_values(self, outputstream):
        return _SymTab.SymTab_print_all_values(self, outputstream)

    def get_symbols_by_class(self, classname, includesubclasses=True):
        return _SymTab.SymTab_get_symbols_by_class(self, classname, includesubclasses)

    def get_all_symbols(self):
        return _SymTab.SymTab_get_all_symbols(self)
    __swig_destroy__ = _SymTab.delete_SymTab
    __del__ = lambda self: None
SymTab_swigregister = _SymTab.SymTab_swigregister
SymTab_swigregister(SymTab)

# This file is compatible with both classic and new-style classes.


