# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_TemperedSimulation')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_TemperedSimulation')
    _TemperedSimulation = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_TemperedSimulation', [dirname(__file__)])
        except ImportError:
            import _TemperedSimulation
            return _TemperedSimulation
        if fp is not None:
            try:
                _mod = imp.load_module('_TemperedSimulation', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _TemperedSimulation = swig_import_helper()
    del swig_import_helper
else:
    import _TemperedSimulation
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class TemperedSimulation(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TemperedSimulation, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TemperedSimulation, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Ninter"] = _TemperedSimulation.TemperedSimulation_Ninter_set
    __swig_getmethods__["Ninter"] = _TemperedSimulation.TemperedSimulation_Ninter_get
    if _newclass:
        Ninter = _swig_property(_TemperedSimulation.TemperedSimulation_Ninter_get, _TemperedSimulation.TemperedSimulation_Ninter_set)
    __swig_setmethods__["use_tempering"] = _TemperedSimulation.TemperedSimulation_use_tempering_set
    __swig_getmethods__["use_tempering"] = _TemperedSimulation.TemperedSimulation_use_tempering_get
    if _newclass:
        use_tempering = _swig_property(_TemperedSimulation.TemperedSimulation_use_tempering_get, _TemperedSimulation.TemperedSimulation_use_tempering_set)
    __swig_setmethods__["tpow"] = _TemperedSimulation.TemperedSimulation_tpow_set
    __swig_getmethods__["tpow"] = _TemperedSimulation.TemperedSimulation_tpow_get
    if _newclass:
        tpow = _swig_property(_TemperedSimulation.TemperedSimulation_tpow_get, _TemperedSimulation.TemperedSimulation_tpow_set)
    __swig_setmethods__["minmc"] = _TemperedSimulation.TemperedSimulation_minmc_set
    __swig_getmethods__["minmc"] = _TemperedSimulation.TemperedSimulation_minmc_get
    if _newclass:
        minmc = _swig_property(_TemperedSimulation.TemperedSimulation_minmc_get, _TemperedSimulation.TemperedSimulation_minmc_set)
    __swig_setmethods__["ITMAX"] = _TemperedSimulation.TemperedSimulation_ITMAX_set
    __swig_getmethods__["ITMAX"] = _TemperedSimulation.TemperedSimulation_ITMAX_get
    if _newclass:
        ITMAX = _swig_property(_TemperedSimulation.TemperedSimulation_ITMAX_get, _TemperedSimulation.TemperedSimulation_ITMAX_set)

    def __init__(self, *args):
        this = _TemperedSimulation.new_TemperedSimulation(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _TemperedSimulation.delete_TemperedSimulation
    __del__ = lambda self: None

    def Reinitialize(self, width, mp):
        return _TemperedSimulation.TemperedSimulation_Reinitialize(self, width, mp)

    def SetNinter(self, N):
        return _TemperedSimulation.TemperedSimulation_SetNinter(self, N)

    def SetItmax(self, N):
        return _TemperedSimulation.TemperedSimulation_SetItmax(self, N)

    def PrintStepDiagnostic(self):
        return _TemperedSimulation.TemperedSimulation_PrintStepDiagnostic(self)

    def GetAcceptance(self):
        return _TemperedSimulation.TemperedSimulation_GetAcceptance(self)

    def GetSwap(self):
        return _TemperedSimulation.TemperedSimulation_GetSwap(self)

    def GetLastCycle(self, u, d):
        return _TemperedSimulation.TemperedSimulation_GetLastCycle(self, u, d)

    def PrintStateDiagnostic(self):
        return _TemperedSimulation.TemperedSimulation_PrintStateDiagnostic(self)

    def GetMixstat(self):
        return _TemperedSimulation.TemperedSimulation_GetMixstat(self)
TemperedSimulation_swigregister = _TemperedSimulation.TemperedSimulation_swigregister
TemperedSimulation_swigregister(TemperedSimulation)
cvar = _TemperedSimulation.cvar

# This file is compatible with both classic and new-style classes.


