// This is really -*- C++ -*-


#ifndef FivePointIntegration_h
#define FivePointLegeIntegration_h

#include <Integration.h>
#include <LikelihoodComputation.h>
  
#include "Serializable.h"


namespace BIE {

  //+ CLICLASS FivePointIntegration SUPER Integration
  /**
     Integrate using just the corners and middle of a tile
  */
  class FivePointIntegration : public Integration {
  public:
    //+ CLICONSTR
    //! Null constructor
     FivePointIntegration();

     //+ CLICONSTR double
     //! Constructor with desired relative error value
     FivePointIntegration(double desiredRelativeError);
     
     //! Destructor
    ~FivePointIntegration();
    
    // void ParameterChange(int nu, int nv);

 
    //! Deprecated. Compute Model Norm with direct calls to model
    double NormValue(Model* m, Tile* t, SampleDistribution* d);
    //! Deprecated. Compute Model valuewith direct calls to model
    vector<double> Value(Model* m, Tile* t, SampleDistribution* d);


    /** Compute value of model over a tile using a likelihoodCompuation
	object as an intermediary.  Calling thread will block until
	integration is completed and function returns.
	Missing:  Need Corresponding NormValue function
    */
    vector<double> Value(LikelihoodComputation* l, Model* m, Tile* t,
			 SampleDistribution* d);


    /** Deprecated. Compute model norm using line-of-sight style
	parallelism with direct calls
    */
    double NormValue(Model* m, Tile* t, SampleDistribution* d,
		     int irank, int nrank);

    /** Deprecated. Compute model value using line-of-sight style
	parallelism with direct calls
    */
    vector<double> Value(Model* m, Tile* t, SampleDistribution* d,
			 int irank, int nrank, MPI_Comm &comm);
    
  private:
    double desiredRelativeError;
    double estimatedError;

    // deprecated: remove    int nU, nV;
    // deprecated: remove   LegeQuad *U, *V;
    
    #ifndef SWIG
    // AUTO GENERATED BY ../persistence/autopersist.py
    private:
    friend class boost::serialization::access;
    template<class Archive>
    void serialize(Archive & ar, const unsigned int version) {
        this->pre_serialize(ar, version);
         try {                                                         
          ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP(Integration);            
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(desiredRelativeError);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(estimatedError);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
        this->post_serialize(ar, version);
    }
    #endif

  };
  
}
#ifndef SWIG
BIE_CLASS_TYPE_INFO(BIE::FivePointIntegration)
BIE_CLASS_EXPORT_KEY(BIE::FivePointIntegration)
#endif
#endif


