// -*- C++ -*-

#ifndef FunnelTest_h
#define FunnelTest_h

#include <LikelihoodFunction.h>
#include <gaussQ.h>

#include "Serializable.h"


namespace BIE {
  
  //+ CLICLASS FunnelTest SUPER LikelihoodFunction
  //! A "user-defined" likelihood function for testing
  //!
  //! Each parameter is normally distributed with a mean of zero and
  //! variance of \f$e^v\f$, following the example given by Radford Neal
  //! (2003).  The first parameter of the vector is the value \f$v\f$.
  //!
  //! @ingroup likefunc
  class FunnelTest : public LikelihoodFunction 
  {
    
  private:
    
    //! Number of dimensions
    int            dim;

    //! Minimum value of "v"
    double         vmin;

    //! Maximum value of "v"
    double         vmax;

    //! Normalization value for "v"
    double         vnorm;

    //! Log normalization value for "v"
    double         lvnorm;

    //! Normalization for the "v" variable
    void normalize()
    { 
      lvnorm = -vmax - log(1.0 - exp(vmin-vmax)); 
      vnorm  = exp(lvnorm);
    }

  public:

    //+ CLICONSTR
    //! Null constructor
    FunnelTest() : dim(10), vmin(-10.0), vmax(10.0) { normalize(); }
    
    //+ CLICONSTR int
    //! Constructor with dimension
    FunnelTest(int d) : dim(d), vmin(-10.0), vmax(10.0) { normalize(); }

    //+ CLICONSTR int double double
    //! Constructor with limits and dimension
    FunnelTest(int d, double vmin, double vmax) : dim(d), vmin(vmin), vmax(vmax)
    { normalize(); }

    //! Destructor
    virtual ~FunnelTest() {}
    
    //! This is likelihood function
    double LikeProb(std::vector<double> &z, SampleDistribution* sd, 
		    double norm, Tile *t, State *s, int indx);
    
    //! The joint cumulative function
    double CumuProb(std::vector<double> &z, SampleDistribution* sd, 
		    double norm, Tile *t, State *s, int indx, Fct1dPtr f);

    //! Label parameters
    const std::string ParameterDescription(int i);

  protected:
    
    #ifndef SWIG
    // AUTO GENERATED BY ../persistence/autopersist.py
    private:
    friend class boost::serialization::access;
    template<class Archive>
    void serialize(Archive & ar, const unsigned int version) {
        this->pre_serialize(ar, version);
         try {                                                         
          ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP(LikelihoodFunction);            
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(dim);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(vmin);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(vmax);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(vnorm);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(lvnorm);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
        this->post_serialize(ar, version);
    }
    #endif

  };

} //namespace BIE

#ifndef SWIG
BIE_CLASS_TYPE_INFO(BIE::FunnelTest)
BIE_CLASS_EXPORT_KEY(BIE::FunnelTest)
#endif
#endif
