// This is -*- C++ -*-

#ifndef GaussTestLikelihoodFunctionMulti_h
#define GaussTestLikelihoodFunctionMulti_h

#include "Serializable.h"


#include <LikelihoodFunction.h>

namespace BIE {

  //+ CLICLASS GaussTestLikelihoodFunctionMulti SUPER LikelihoodFunction
  //! A "user-defined" likelihood function for testing
  //! 
  //! By default, the "data" is the combination of two one-dimensional
  //! Gaussians, one at 0.2 with variance of 0.03 and one at 0.9 with
  //! variance of 0.03 with 50% weights each.
  //! 
  //! The default model, including the number of components in the
  //! mixture, may be changed at construction.
  //! 
  //! The variance may be modeled or fixed (using the SetDim member).
  //! 
  //! This model is similar to GaussTestLikelihoodFunction but this
  //! version of the model allows data aggregation by powers of two and
  //! multiple level resolution.  The global variable current_level sets
  //! the number of bins in LikeProb.
  //! @ingroup likefunc
  class GaussTestLikelihoodFunctionMulti : public LikelihoodFunction 
  {

  private:

    deque < vector<double> > fdata;
    deque <int> nbins;
    deque <double> dx;
    vector <double> pdata;
    vector <int>    cdata;

    double xmin, xmax;
    unsigned nmix;
    int dim;
    int ptwo;
    int N;
    int levels;
    bool point;

    vector <double> centers, variance, weights;

 public:

    //+ CLICONSTR
    //! Null constructor
    GaussTestLikelihoodFunctionMulti();

    //+ CLICONSTR int int int
    /** Constructor where
	@param Ptwo is the power of two exponent for the number of bins
	@param N0 is the sample size points
	@param Levels is the number of partitions
     */
    GaussTestLikelihoodFunctionMulti(int Ptwo, int N0, int Levels);

    //+ CLICONSTR int int int clivectord* clivectord* clivectord*
    /** Constructor where
	@param Ptwo is the power of two exponent for the number of bins
	@param N0 is the sample size points
	@param Levels is the number of partitions
	The input vectors 
	@param cen0 are the component centers
	@param var0 are the component variances
	@param wgt0 are the weight values for the sampled model.

	The number of components is determined
	from the rank of the input vectors (which must agree!)
     */
    GaussTestLikelihoodFunctionMulti(int Ptwo, int N0, int Levels,
				     clivectord* cen0,
				     clivectord* var0,
				     clivectord* wgt0);

    //+ CLICONSTR int int
    /** Constructor where
	@param N0 is the sample size points
	@param Levels is the number of partitions
     */
    GaussTestLikelihoodFunctionMulti(int N0, int Levels);

    //+ CLICONSTR int int clivectord* clivectord* clivectord*
    /** Constructor for a point likelihood function with a sample size
	where
	@param N0 is the sample size
	@param Levels is the number of partitions
	The input vectors 
	@param cen0 are the component centers
	@param var0 are the component variances
	@param wgt0 are the weight values for the sampled model.

	The number of components is determined
	from the rank of the input vectors (which must agree!)

     */
    GaussTestLikelihoodFunctionMulti(int N0, int Levels,
				     clivectord* cen0,
				     clivectord* var0,
				     clivectord* wgt0);


    //+ CLIMETHOD void SetLevels int
    //! Set number levels
    void SetLevels(int n);

    //+ CLIMETHOD void SetDim int
    //! Set data dimension (currently 1 or 2)
    void SetDim(int n);

    //+ CLIMETHOD void PrintData
    //! Print data to a file for the current level
    void PrintData();

    //! This is likelihood function
    double LikeProb(std::vector<double> &z, SampleDistribution* sd, 
		    double norm, Tile *t, State *s, int indx);

    //! This is joint cumulative probability function
    double CumuProb(std::vector<double> &z, SampleDistribution* sd, 
		    double norm, Tile *t, State *s, int indx, Fct1dPtr f);

    //! Label parameters.  Scheduled for removal.
    const std::string ParameterDescription(int i);

 protected:

    //! Make the synthetic binned data
    void makeSyntheticData();

    //! Make the synthetic point data
    void makeSyntheticPointData();

    //! Make data arrays
    void makeArrays();

    #ifndef SWIG
    // AUTO GENERATED BY ../persistence/autopersist.py
    private:
    friend class boost::serialization::access;
    template<class Archive>
    void serialize(Archive & ar, const unsigned int version) {
        this->pre_serialize(ar, version);
         try {                                                         
          ar & BOOST_SERIALIZATION_BASE_OBJECT_NVP(LikelihoodFunction);            
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(fdata);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(nbins);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(dx);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(pdata);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(cdata);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(xmin);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(xmax);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(nmix);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(dim);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(ptwo);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(N);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(levels);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(point);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(centers);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(variance);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
         try {                                                         
          ar & BOOST_SERIALIZATION_NVP(weights);                        
          BIE_CATCH_BOOST_SERIALIZATION_EXCEPTION;                     
         }                                                             
        this->post_serialize(ar, version);
    }
    #endif

  };

} // namespace BIE

#ifndef SWIG
BIE_CLASS_TYPE_INFO(BIE::GaussTestLikelihoodFunctionMulti)
BIE_CLASS_EXPORT_KEY(BIE::GaussTestLikelihoodFunctionMulti)
#endif
#endif
