# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_AsciiLexer', [dirname(__file__)])
        except ImportError:
            import _AsciiLexer
            return _AsciiLexer
        if fp is not None:
            try:
                _mod = imp.load_module('_AsciiLexer', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _AsciiLexer = swig_import_helper()
    del swig_import_helper
else:
    import _AsciiLexer
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class AsciiLexer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, AsciiLexer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, AsciiLexer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _AsciiLexer.new_AsciiLexer(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _AsciiLexer.delete_AsciiLexer
    __del__ = lambda self: None

    def nextToken(self):
        return _AsciiLexer.AsciiLexer_nextToken(self)

    def tokenText(self):
        return _AsciiLexer.AsciiLexer_tokenText(self)
    AL_NEWLINE_ = _AsciiLexer.AsciiLexer_AL_NEWLINE_
    AL_INT_KEYWORD_ = _AsciiLexer.AsciiLexer_AL_INT_KEYWORD_
    AL_REAL_KEYWORD_ = _AsciiLexer.AsciiLexer_AL_REAL_KEYWORD_
    AL_BOOL_KEYWORD_ = _AsciiLexer.AsciiLexer_AL_BOOL_KEYWORD_
    AL_STRING_KEYWORD_ = _AsciiLexer.AsciiLexer_AL_STRING_KEYWORD_
    AL_STRING_VALUE_ = _AsciiLexer.AsciiLexer_AL_STRING_VALUE_
    AL_INT_VALUE_ = _AsciiLexer.AsciiLexer_AL_INT_VALUE_
    AL_REAL_VALUE_ = _AsciiLexer.AsciiLexer_AL_REAL_VALUE_
    AL_COMMA_ = _AsciiLexer.AsciiLexer_AL_COMMA_
    AL_EQUALS_ = _AsciiLexer.AsciiLexer_AL_EQUALS_
    AL_LEFT_CURLY_ = _AsciiLexer.AsciiLexer_AL_LEFT_CURLY_
    AL_RIGHT_CURLY_ = _AsciiLexer.AsciiLexer_AL_RIGHT_CURLY_
    AL_LEFT_SQUAREBRACKET_ = _AsciiLexer.AsciiLexer_AL_LEFT_SQUAREBRACKET_
    AL_ATRATE_ = _AsciiLexer.AsciiLexer_AL_ATRATE_
    AL_EOF_ = _AsciiLexer.AsciiLexer_AL_EOF_
    AL_ERROR_ = _AsciiLexer.AsciiLexer_AL_ERROR_
AsciiLexer_swigregister = _AsciiLexer.AsciiLexer_swigregister
AsciiLexer_swigregister(AsciiLexer)

# This file is compatible with both classic and new-style classes.


