# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Distribution', [dirname(__file__)])
        except ImportError:
            import _Distribution
            return _Distribution
        if fp is not None:
            try:
                _mod = imp.load_module('_Distribution', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Distribution = swig_import_helper()
    del swig_import_helper
else:
    import _Distribution
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class Distribution(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Distribution, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Distribution, name)
    __repr__ = _swig_repr
    UniformAdd = _Distribution.Distribution_UniformAdd
    UniformMult = _Distribution.Distribution_UniformMult
    NormalAdd = _Distribution.Distribution_NormalAdd
    NormalMult = _Distribution.Distribution_NormalMult
    Undefined = _Distribution.Distribution_Undefined

    def __init__(self):
        this = _Distribution.new_Distribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _Distribution.delete_Distribution
    __del__ = lambda self: None

    def New(self):
        return _Distribution.Distribution_New(self)

    def PDF(self, arg2):
        return _Distribution.Distribution_PDF(self, arg2)

    def logPDF(self, arg2):
        return _Distribution.Distribution_logPDF(self, arg2)

    def CDF(self, arg2):
        return _Distribution.Distribution_CDF(self, arg2)

    def lower(self):
        return _Distribution.Distribution_lower(self)

    def upper(self):
        return _Distribution.Distribution_upper(self)

    def Mean(self):
        return _Distribution.Distribution_Mean(self)

    def StdDev(self):
        return _Distribution.Distribution_StdDev(self)

    def Moments(self, arg2):
        return _Distribution.Distribution_Moments(self, arg2)

    def Sample(self):
        return _Distribution.Distribution_Sample(self)

    def setWidth(self, x):
        return _Distribution.Distribution_setWidth(self, x)

    def Type(self):
        return _Distribution.Distribution_Type(self)

    def Dim(self):
        return _Distribution.Distribution_Dim(self)
Distribution_swigregister = _Distribution.Distribution_swigregister
Distribution_swigregister(Distribution)

class SampleDistribution(Distribution):
    __swig_setmethods__ = {}
    for _s in [Distribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SampleDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [Distribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SampleDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distribution.delete_SampleDistribution
    __del__ = lambda self: None

    def CDF(self, arg2):
        return _Distribution.SampleDistribution_CDF(self, arg2)

    def New(self):
        return _Distribution.SampleDistribution_New(self)

    def AccumData(self, *args):
        return _Distribution.SampleDistribution_AccumData(self, *args)

    def ComputeDistribution(self):
        return _Distribution.SampleDistribution_ComputeDistribution(self)

    def numberData(self):
        return _Distribution.SampleDistribution_numberData(self)

    def getValue(self, i):
        return _Distribution.SampleDistribution_getValue(self, i)

    def getdim(self, i):
        return _Distribution.SampleDistribution_getdim(self, i)

    def getRecordType(self):
        return _Distribution.SampleDistribution_getRecordType(self)

    def getDataSetSize(self):
        return _Distribution.SampleDistribution_getDataSetSize(self)
SampleDistribution_swigregister = _Distribution.SampleDistribution_swigregister
SampleDistribution_swigregister(SampleDistribution)

class BinnedDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BinnedDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BinnedDistribution, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __swig_destroy__ = _Distribution.delete_BinnedDistribution
    __del__ = lambda self: None

    def New(self):
        return _Distribution.BinnedDistribution_New(self)

    def getLow(self, i):
        return _Distribution.BinnedDistribution_getLow(self, i)

    def getHigh(self, i):
        return _Distribution.BinnedDistribution_getHigh(self, i)

    def CDF(self, arg2):
        return _Distribution.BinnedDistribution_CDF(self, arg2)
BinnedDistribution_swigregister = _Distribution.BinnedDistribution_swigregister
BinnedDistribution_swigregister(BinnedDistribution)

class PointDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PointDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, PointDistribution, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _Distribution.new_PointDistribution(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _Distribution.delete_PointDistribution
    __del__ = lambda self: None

    def New(self):
        return _Distribution.PointDistribution_New(self)

    def getRecordType(self):
        return _Distribution.PointDistribution_getRecordType(self)

    def AccumData(self, v, datapoint):
        return _Distribution.PointDistribution_AccumData(self, v, datapoint)

    def getdim(self, i):
        return _Distribution.PointDistribution_getdim(self, i)

    def numberData(self):
        return _Distribution.PointDistribution_numberData(self)

    def getValue(self, i):
        return _Distribution.PointDistribution_getValue(self, i)

    def Point(self):
        return _Distribution.PointDistribution_Point(self)

    def CDF(self, v):
        return _Distribution.PointDistribution_CDF(self, v)
PointDistribution_swigregister = _Distribution.PointDistribution_swigregister
PointDistribution_swigregister(PointDistribution)

class NullDistribution(SampleDistribution):
    __swig_setmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, NullDistribution, name, value)
    __swig_getmethods__ = {}
    for _s in [SampleDistribution]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, NullDistribution, name)
    __repr__ = _swig_repr

    def __init__(self):
        this = _Distribution.new_NullDistribution()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _Distribution.delete_NullDistribution
    __del__ = lambda self: None

    def New(self):
        return _Distribution.NullDistribution_New(self)
NullDistribution_swigregister = _Distribution.NullDistribution_swigregister
NullDistribution_swigregister(NullDistribution)

# This file is compatible with both classic and new-style classes.


